d={}
name=input("enter friends name:")
lang=input("enter a language:")
d.update({name:lang})
name=input("enter friends name:")
lang=input("enter a language:")
d.update({name:lang})
name=input("enter friends name:")
lang=input("enter a language:")
d.update({name:lang})
name=input("enter friends name:")
lang=input("enter a language:")
d.update({name:lang})
print(d)